### ISSUE TITLE
Can`t generate extension

### ISSUE THREAD

**Issue by piotrburda** [YolfTypo3/SavLibraryKickstarterProject#1]
everytime when try to generate one (other are working fine) extension, i have this error
Fatal error: Class 'SAV\SavLibraryKickstarter\ViewHelpers\RuntimeException' not found in .../typo3conf/ext/sav_library_kickstarter/Classes/ViewHelpers/FunctionViewHelper.php on line 392.

After analise of files i know that the kickstarter is unable to write changes to SavLibraryPlus.xml file. But i din`t know why

**Comment by YolfTypo3** [comment]
Closed
